app:
  name: "web_app"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "172.16.234.109"
  port: 3306
  user: "tkchina"
  password: "123456"
  dbname: "tkchina"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: ""
  port: 6379
  password: ""
  db: 0
  pool_size: 100